<label for="comment"><?php echo _e( 'Admin comment:', 'post-type-newspages' ); ?>
    <textarea id="comment" name="admin comment" rows="5" cols="26"> <?php echo $comment; ?></textarea>
</label>

<label for="status"><?php echo _e( 'Alternative title:', 'post-type-newspages' ); ?>
    <input id="alter_title" name="alternative title" type="text" size="28" value="<?php echo $alternative_title; ?>"/>
</label>