<p>
    <label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php echo _e( 'Title:', 'post-type-newspages' ); ?></label>
    <input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>"
           name="<?php echo $this->get_field_name( 'title' ); ?>" type="text"
           value="<?php echo $instance['title']; ?>" />
</p>
<p>
    <label for="<?php echo $this->get_field_id( 'numnewspages' ); ?>"><?php echo _e( 'Number of shown NewsPages:' , 'post-type-newspages' ); ?></label>
    <input class="widefat" id="<?php echo $this->get_field_id( 'numnewspages' ); ?>"
           name="<?php echo $this->get_field_name( 'numnewspages' ); ?>" type="text"
           value="<?php echo esc_attr( $numnewspages ); ?>" />
</p>
